version: '3.9'

networks:
  rental-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rental-app
    ports:
      - '3000:3000'
    env_file: 
      - ./.env # Spécifie le fichier .env utilisé
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - db
    networks:
      - rental-network

  db:
    image: postgres:14
    container_name: rentalappdb
    restart: always
    env_file: 
      - ./.env # Spécifie le fichier .env utilisé
    ports:
      - '5433:5432' # Map 5433 sur l'hôte au port interne 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rental-network

volumes:
  postgres-data:
