version: '3.9'

networks:
  rental-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rental-app
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app # Mount the project directory into the container
      - /usr/src/app/node_modules # Prevent node_modules overwriting
    env_file:
      - ./.env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - db
    command: npm run start:dev # Use the NestJS development script
    networks:
      - rental-network

  db:
    image: postgres:14
    container_name: rentalappdb
    restart: always
    env_file:
      - ./.env
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - rental-network
  
volumes:
  postgres-data:
