version: '3.9'

networks:
  rental-network: # Custom bridge network
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rental-app
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db # Service name of the database container
      DATABASE_PORT: 5432 # Internal port of the database container
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: culturedb
    depends_on:
      - db
    networks:
      - rental-network

  db:
    image: postgres:14
    container_name: rentalappdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: culturedb
    ports:
      - '5433:5432' # Map 5433 on the host to 5432 in the container
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rental-network

volumes:
  postgres-data:
